export const Color = {
  "chartColor-blue": "#0011F6",
  "chartColor-mainBlue": "#3240FF",
  "chartColor-lightBlue": "#3C91FF",
  "chartColor-nautical": "#48E3FF",
  "chartColor-turquoise": "#0BFFDB",
  "chartColor-lightViolet": "#BB9CFF",
  "chartColor-violet": "#8122FF",
  "chartColor-red": "#FD005C",
  "chartColor-lightRed": "#FF8BAA",
  "styleColors-mainGray": "#2A3F58",
  "styleColors-darkGray": "#72809D",
  "styleColors-gray": "#CCD2DE",
  "styleColors-lightGray": "#FDF2F5",
  "styleColors-lightBlue": "#F4F7FC",
  "styleColors-greyBlue": "#DBE9FF",
  "systemColors-success": "#A7E521",
  "systemColors-info": "#03C3EC",
  "systemColors-alert": "#FFD422",
  "systemColors-error": "#EF3F26",
} as const;
